# Generated by Django 3.1.2 on 2020-10-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyshoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
