# Generated by Django 3.1.2 on 2020-10-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyshoes', '0003_purchase_shoesinpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='purchase',
            name='client_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
