# Generated by Django 3.1.2 on 2020-10-29 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyshoes', '0006_auto_20201029_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='buyshoes.shoe'),
        ),
    ]
